version: '3.3'

#env_file: .env

services:
  db:
    image: postgres_pgtap:latest
    restart: always
    container_name: dev_db
    # don't expose ports in production
    ports:
      - 6543:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=${PGUSER_DOCKER}
      - POSTGRES_PASSWORD=${PGPASS_DOCKER}

# volumes:
#   maildata:
#     driver: local
#   mailstate:
#     driver: local
